# Generated by Django 2.0 on 2017-12-28 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('label', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('shortenURL', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('targetURL', models.CharField(max_length=500)),
            ],
        ),
    ]
