# Generated by Django 2.0 on 2017-12-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shortenURL',
            field=models.TextField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
