# Generated by Django 2.0 on 2017-12-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_auto_20171228_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='linkid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='shortenURL',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
