# Generated by Django 2.0 on 2017-12-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_auto_20171228_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='linkid',
        ),
        migrations.AddField(
            model_name='link',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
