# Generated by Django 2.0 on 2017-12-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_auto_20171228_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='label',
        ),
    ]
